[package]
name = "cutils"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "cutils"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
solana-program = "1.14.18"
spl-account-compression = { version="0.1.8", features = ["cpi"] }
mpl-bubblegum = { version = "0.7.0", features = ["no-entrypoint", "cpi"] }

# Added due to anchor and solana-cli wonkyness as of late
getrandom = { version = "0.2.10", features = ["custom"] }
winnow = "=0.4.1"
toml_datetime = "=0.6.1"