[workspace]
members = [
    #basics
    "basics/account-data/native/program",
    "basics/account-data/anchor/programs/anchor-program-example",
    "basics/checking-accounts/native/program",
    "basics/checking-accounts/anchor/programs/anchor-program-example",
    "basics/close-account/native/program",
    "basics/close-account/anchor/programs/close-account",
    "basics/counter/native/program",
    "basics/counter/anchor/programs/counter_anchor",
    "basics/counter/mpl-stack",
    "basics/create-account/native/program",
    "basics/create-account/anchor/programs/create-system-account",
    "basics/cross-program-invocation/native/programs/*",
    "basics/cross-program-invocation/anchor/programs/*",
    "basics/hello-solana/native/program",
    "basics/hello-solana/anchor/programs/*",
    "basics/pda-rent-payer/native/program",
    "basics/pda-rent-payer/anchor/programs/*",
    "basics/processing-instructions/native/program",
    "basics/processing-instructions/anchor/programs/*",
    "basics/program-derived-addresses/native/program",
    "basics/program-derived-addresses/anchor/programs/*",
    "basics/realloc/native/program",
    "basics/rent/native/program",
    "basics/rent/anchor/programs/*",
    "basics/repository-layout/native/program",
    "basics/repository-layout/anchor/programs/*",
    "basics/transfer-sol/native/program",
    "basics/transfer-sol/anchor/programs/*"
]
resolver = "2"
