[package]
name = "car-rental-service"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.3"
shank = "0.0.12"
solana-program = "1.14.13"

[lib]
crate-type = ["cdylib", "lib"]
