[features]
seeds = false
skip-lint = false
[programs.localnet]
hand = "9rN5nSQBX1gcbweshWAfRE4Ccv5puJfxUJhqKZ5BEdoP"
lever = "4wFN9As94uDgcBK9umEi6DNjRLi8gq7jaHwSw3829xq8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
