[package]
name = "close-account-native-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "1.5.1"
solana-program = "=1.18.17"

[lib]
crate-type = ["cdylib", "lib"]
