name: Anchor Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      
      - name: Install dependencies
        run: |
          npm install -g @project-serum/anchor

      - name: Build Solana Programs
        run: |
          declare -a StringArray=(
            "basics/account-data/anchor"
            "basics/checking-accounts/anchor"
            "basics/close-account/anchor"
            "basics/counter/anchor"
            "basics/create-account/anchor"
            "basics/cross-program-invocation/anchor"
            "basics/hello-solana/anchor"
            "basics/pda-rent-payer/anchor"
            "basics/processing-instructions/anchor"
            "basics/program-derived-addresses/anchor"
            "basics/realloc/anchor"
            "basics/rent/anchor"
            "basics/repository-layout/anchor"
            "basics/transfer-sol/anchor"
            "compression/cnft-vault/anchor"
            "oracles/pyth/anchor"
            "tokens/create-token/anchor"
            "tokens/nft-minter/anchor"
            "tokens/pda-mint-authority/anchor"
            "tokens/spl-token-minter/anchor"
            "tokens/token-2022/basics/anchor"
            "tokens/transfer-tokens/anchor"
          )
          for val in "${StringArray[@]}"; do
             echo "Building $val..."
             cd $val
             anchor build
             cd - > /dev/null
          done
