name: Native Programs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: solanadevelopers/solana-workshop-image
    strategy:
      matrix:
        {
          dir:
            [
              "basics/account-data/native/program",
              "basics/checking-accounts/native/program",
            ],
        }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build program
        working-directory: ${{ matrix.dir }}
        run: cargo build-sbf --verbose
