name: Native Programs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: docker.io/solanadevelopers/solana-workshop-image:0.0.2
    strategy:
      matrix:
        {
          dir:
            [
              "basics/account-data/native/program",
              "basics/checking-accounts/native/program",
              "basics/close-account/native/program",
              "basics/counter/native",
              "basics/create-account/native/program",
              "basics/cross-program-invocation/native/program",
              "basics/hello-solana/native/program",
              "basics/pda-rent-payer/native/program",
              "basics/processing-instructions/native/program",
              "basics/program-derived-addresses/native/program",
              "basics/realloc/native/program",
              "basics/rent/native/program",
              "basics/repository-layout/native/program",
              "basics/transfer-sol/native/program",
            ],
        }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build program
        working-directory: ${{ matrix.dir }}
        run: cargo build-sbf --verbose
